# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d88b6aaf01144e383ff16271086e46d5d7d5acc0ffdc05efbe7a8a141b1a0b8c74a6e8251d0637b34659dcdb0f333a7ac347f62745f890a68462dfa4c6b8eb10

test:
  secret_key_base: f96f32f3398cd1193d963357be8911b390ead9eea51f3643afd665a92f5b2101ca8101d608459dabe1903c8d4e48b0fdc3f60a950e1960bdf7c27a24c4423412

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
